name: Deploy Infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-deploy.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  contents: read
  pull-requests: write

env:
  TF_LOG: INFO

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Create terraform.tfvars file from secrets
    - name: Create terraform.tfvars
      run: |
        cat > terraform.tfvars << EOF
        aws_region        = "${{ secrets.AWS_REGION }}"
        vpc_id            = "${{ secrets.VPC_ID }}"
        project_name      = "hrgoat-${{ github.event.inputs.environment || 'dev' }}"
        ec2_ami_id        = "${{ secrets.EC2_AMI_ID }}"
        ec2_instance_type = "${{ secrets.EC2_INSTANCE_TYPE }}"
        key_name          = "${{ secrets.KEY_NAME }}"
        db_instance_class = "${{ secrets.DB_INSTANCE_CLASS }}"
        db_username       = "${{ secrets.DB_USERNAME }}"
        db_password       = "${{ secrets.DB_PASSWORD }}"
        EOF

    # Configure AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan
      
    # Save plan to artifacts
    - name: Save Terraform Plan
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: terraform/tfplan
        
    # Apply the Terraform plan
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      run: terraform apply -auto-approve tfplan
      
    # Output the deployment information
    - name: Output Deployment Info
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      run: |
        echo "EC2 Public IP: $(terraform output -raw ec2_instance_public_ip)" >> $GITHUB_STEP_SUMMARY
        echo "EC2 Public DNS: $(terraform output -raw ec2_instance_public_dns)" >> $GITHUB_STEP_SUMMARY
        echo "RDS Endpoint: $(terraform output -raw rds_endpoint)" >> $GITHUB_STEP_SUMMARY
        
        # Save outputs as environment variables for the next job
        echo "EC2_PUBLIC_IP=$(terraform output -raw ec2_instance_public_ip)" >> $GITHUB_ENV
        echo "RDS_ENDPOINT=$(terraform output -raw rds_endpoint)" >> $GITHUB_ENV
        echo "RDS_USERNAME=$(terraform output -raw rds_username)" >> $GITHUB_ENV
        
    # Save terraform outputs to artifacts
    - name: Save Terraform Outputs
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      run: |
        mkdir -p ../terraform-outputs
        terraform output -json > ../terraform-outputs/outputs.json
        
    - name: Upload Terraform Outputs
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: terraform-outputs
        path: terraform-outputs/ 